"use client";

import { useState, useEffect } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import SessionProvider from "./SessionProvider";
import HeaderNavBar from "@/components/HeaderNavBar";
import { UserLocationContext } from "@/context/UserLocationContext";

const raleway = Raleway({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [userLocation, setUserLocation] = useState({});

  const getUserLocation = () => {
    navigator.geolocation.getCurrentPosition((pos) => {
      setUserLocation({ lat: pos.coords.latitude, lng: pos.coords.longitude });
    });
  };

  useEffect(() => {
    getUserLocation();
  }, []);
  return (
    <html lang="en">
      <body className={raleway.className}>
        <SessionProvider>
          <UserLocationContext.Provider
            value={{ userLocation, setUserLocation }}
          >
            <HeaderNavBar />
            {children}
          </UserLocationContext.Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
